# Generated by Django 4.1.3 on 2022-11-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0003_remove_users_age_review_rating_review_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistsUser',
            new_name='ArtistsProfile',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, default='INR', max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/Profile')),
                ('profile_headline', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_artist', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='artistsprofile',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
