# Generated by Django 4.1.3 on 2022-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_profile_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsprofile',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='artistsprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/'),
        ),
    ]
