# Generated by Django 4.1.3 on 2022-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_artistsprofile_fee_alter_artistsprofile_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsprofile',
            name='on_break',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
