# Generated by Django 4.1.3 on 2022-11-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_artistsprofile_on_break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_artist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
