# Generated by Django 4.1.3 on 2022-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_profile_is_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsprofile',
            name='genre',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Cinematography', 'Cinematography'), ('DJ', 'DJ'), ('Singer', 'Singer'), ('Dancer', 'Dancer'), ('Choreographers', 'Choreographers'), ('Others', 'Others')], default='Photography', max_length=255),
        ),
    ]
