# Generated by Django 4.1.3 on 2022-11-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_profile_profile_photo_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(null=True)),
                ('valid_upto', models.DateTimeField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
    ]
