# Generated by Django 4.1.3 on 2023-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_remove_profile_profile_photo_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo_thumb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
