# Generated by Django 4.1.3 on 2023-04-15 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0017_profile_profile_photo_thumb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_directions', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_instructions', models.URLField(blank=True, null=True)),
                ('expected_footfall', models.IntegerField(blank=True, null=True)),
                ('event_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True)),
                ('accomodation', models.CharField(blank=True, max_length=200, null=True)),
                ('accomodation_address', models.TextField(blank=True, null=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.artistsprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('week_days', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=50, null=True)),
                ('availability_choices', models.CharField(blank=True, choices=[('RECURRING', 'Recurring'), ('OCCASIONAL', 'Occasional'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], max_length=50, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
    ]
