# Generated by Django 4.1.3 on 2023-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_availability_choices_availability_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='end_date',
            field=models.TimeField(blank=True, default='23:59:00', null=True),
        ),
    ]
