# Generated by Django 4.1.3 on 2023-04-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_dates_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dates',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='dates',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
